image: golang

stages:
    - test

variables:
  NATS_URI: nats://nats:4222

.test:
    image: golang
    stage: test
    before_script:
      - go mod download


format:
    extends: .test
    script:
      - go fmt ./...

test:
    extends: .test
    services:
      - nats
    script:
      - go test -v ./...

